### ISSUE TITLE
888 GRAND CONCOURSE is "not recognized" in DDO search

### ISSUE THREAD

**Issue by sraby** [JustFixNYC/tenants2#975] opened 2020-01-14 20:08 UTC
![image](https://user-images.githubusercontent.com/12834575/72378591-b295f380-36df-11ea-865c-2090ad9451e9.png)

**Comment by sraby** [comment] 2020-01-14 20:10
Oddly enough, Who Owns What has no trouble searching this address, so it shouldn't be a Geosearch Issue.

Also, DDO handles the address 800 GRAND CONCOURSE fine, so it also shouldn't have to do with the odd street name...

**Comment by toolness** [comment] 2021-08-09 14:12
Hmm, either our open data changed or one of the more recent changes made to DDO fixed this: https://demo.justfix.nyc/en/?address=888%20GRAND%20CONCOURSE&borough=BRONX

I'm going to go ahead and close this issue since it can no longer be reproduced.

**Closed by toolness** 2021-08-09 14:12 UTC
