### ISSUE TITLE
Node-sass doesn't pick up on SASS _ files

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants2#300] opened 2018-10-19 20:49 UTC

**Comment by toolness** [comment] 2018-10-20 14:44
Wait, uh, I'm actually unable to reproduce this on my end using Docker, which is weird... But I definitely _have_ run into weird situations where I'm editing our SASS and the SASS watcher somehow doesn't pick up on the changes--it just seems to happen intermittently and I'm not sure how to reproduce the problem consistently. Blurgh!

**Comment by toolness** [comment] 2019-02-01 22:33
FWIW, I just fixed another funky "dev setup won't notice that some files have changed" issue in 0c2c4a92e55d724af06a67e522884b10203562b2, which may have mistakenly been attributed to this in the past, I'm not sure.

**Comment by toolness** [comment] 2019-06-26 10:54
Hmm, given that I've been unable to reproduce this, I'm closing this issue. If we encounter it again we can re-open it, preferably with exact steps to reproduce.

**Comment by toolness** [comment] 2020-04-12 20:11
The problem is that node-sass won't notice changes in _new_ files, e.g. if we add a `_boop.scss` and import it in `styles.scss`, it won't notice any changes in `_boop.scss`.  It looks like this is still an open issue at https://github.com/sass/node-sass/issues/1891.

**Closed** 2020-04-12 20:33 UTC
